# go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_SLEEP=y

#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# MOUSE
CONFIG_ZMK_MOUSE=n

# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

CONFIG_ZMK_SPLIT=y

# ESB config
# disable BLE on peripheral
# NOTE: keep default (=y) if want to pairing BLE host on split central, or wireless dongle
CONFIG_ZMK_BLE=n

# disable default split transport on central and peripheral
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n

# # enable split esb transport
CONFIG_ZMK_SPLIT_ESB=y

# another IMPORTANT config for ESB
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=32
# CONFIG_ESB_PIPE_COUNT=2

# currently, set ESB_TX_FIFO to 1, to workaround ACK issues before NCS 3.1.0 release
# NOTE: should apply to both TX and RX sides
# CONFIG_ESB_TX_FIFO_SIZE=2

# Logging!
CONFIG_ZMK_SPLIT_ESB_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

CONFIG_ZMK_POINTING=y

CONFIG_ESB_TX_RINGBUF=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y

CONFIG_ESB_POLLING_RATE_2KHZ=y
# CONFIG_ZMK_SPLIT_ESB_USE_WORK_QUEUE_DEDICATED=y
# CONFIG_ZMK_SPLIT_ESB_SEND_WHOLE_KEY=y
# CONFIG_WATCHDOG=y

CONFIG_ESB_HFCLK_OFF_EVERY_TX=n
CONFIG_ESB_FAST_SWITCHING_PERIPHERAL=n
CONFIG_ESB_DISABLE_IRQ_TX=y